application: escape-3ds
version: 0
runtime: go
api_version: go1

inbound_services:
- mail

handlers:
- url: /client
  static_dir: client

- url: /debug
  login: admin
  script: _go_app

- url: /.*
  script: _go_app